name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  unitTest:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code # git clone
        uses: actions/checkout@v3
      - name: setup node # this is where we install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install node modules # npm install
        run: npm ci
        working-directory: ./green-foods
      - name: run tests # npm test
        run: npm test
        working-directory: ./green-foods